//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _27._01._2022.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ClientProduct = new HashSet<ClientProduct>();
        }
    
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public int IDType { get; set; }
        public decimal Price { get; set; }
        public string Warranty { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProduct> ClientProduct { get; set; }
        public virtual Type Type { get; set; }
    }
}
